[package]
name = "conquer-reclaim-util"
description = "utilities for implementing memory reclamation mechanis"
version = "0.1.0"
authors = ["Oliver Giersch"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
